version: "3.9"
services:
  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
